sudo: required
dist: trusty



before_install:
  - sudo apt-get update
  - sudo apt-get install -y squashfs-tools multistrap e2fsprogs e2tools

before_script:
  - cat /etc/hosts
  - ./.setup-sandbox-for-travis.sh
  - ./.setup-web-for-travis.sh

script:
  - cd uml
  - ./run-test-exercise.sh
  - cd ../web
  - rvmsudo ./webapp.rb start
  - sleep 20
  - curl 127.0.0.1:3001/status.json
  - cat log/*
  - rvmsudo rake test

after_failure:
  - cat /tmp/build.log
